//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Defecto_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Defecto_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
  
    ViewBag.Title = "Defecto";


#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
using (Html.BeginForm())
{


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
                        



#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
__o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
   __o = Html.LabelFor(model => model.DescripcionDefecto, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
       __o = Html.EditorFor(model => model.DescripcionDefecto, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.DescripcionDefecto, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
   __o = Html.LabelFor(model => model.TipoDefecto, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
       __o = Html.DropDownList("TipoDefecto", new SelectList(ViewBag.TiposDefecto, "Value", "Text"), new { @class = "form-control" } );


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.TipoDefecto, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
      
}

#line default
#line hidden
DefineSection("Scripts", () => {


#line 14 "C:\Users\user\AppData\Local\Temp\BE002E2A76BDDD952D93DF5C028FC4DB41B9\10\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Defecto\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
