//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
      
    ViewBag.Title = "Modelo";
    

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
   __o = Html.ActionLink("Crear Nuevo Modelo", "Create", "Modelo", new { @class = "btn" });


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Denominacion);


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayNameFor(model => model.LimiteInferiorDeObservado);


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayNameFor(model => model.LimiteInferiorDeReproceso);


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayNameFor(model => model.LimiteSuperiorDeObservado);


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayNameFor(model => model.LimiteSuperiorDeReproceso);


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
        foreach (var item in Model) {
        

#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Denominacion);


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.LimiteInferiorDeObservado);


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.LimiteInferiorDeReproceso);


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.LimiteSuperiorDeObservado);


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.LimiteSuperiorDeReproceso);


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.ActionLink("Editar", "Edit", new { id=item.Sku }, new { @class = "btn" });


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.ActionLink("Detalles", "Details", new { id=item.Sku }, new { @class = "btn" });


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
           __o = Html.ActionLink("Eliminar", "Delete", new { id=item.Sku }, new { @class = "btn" });


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
             
}

#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Modelo\Index.cshtml"
   __o = Html.ActionLink("Volver al Inicio", "Index", "Home", null , new{ @class = "btn" } );


#line default
#line hidden
}
}
}
