//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                  
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        if (role == "Admin")
        {
            

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
              
          rl.Aion("Index", "LineaDeProduccion");

        }ntesws\Home\Index.cshtml"
     Url.Action("Index", "Defecto")             
        }



    }

#line default
#line hidden                  
        if (rUrl.Action("Index", "LineaDeProduccion")ole == "AdmiUrl.Action("Index", "LineaDeProduccion")n" || role == "SuperLinea")
        colUrl.Action("Index", "Defecto")-md-2">--   Url.Action("Index", "LineaDeProduccion")             <h2>Ordenes-de-Produccio            

n</h2>
             

                       on</            
p>
                <p><                                   __o = Url.Action("Index", "Turno");i'@c
orrect behavior and will be lost if
//     the c'>O     Url.Action("Index", "Defecto")       

rdenes &raquoo</                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B3            

8D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtml"
a></p>er            
</div>IO;
u

#line default
#line hidden

#line 20 .C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D8Url.Action("Index", "Turno")0\u\ControlDeCalzado2\SistemaGestionDeClientes\Views\Home\Index.cshtmls44                                   __o232lDeCalzado2\SistemaGeTurnoies

  #line4default59#lineehiddenrole#lineS21 .C:\Users\user\AppDa       

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DE240FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Ho25\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
	{
		if (role == "Admin")
		{
			

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
			

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

		}
		if (role == "Admin" || role == "SuperLinea")
		{
			

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
		}

		

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              

		
	}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Home_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Home_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                   
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
	{
		if (role == "Admin")
		{
			

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
			

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

		}
		if (role == "Admin" || role == "SuperLinea")
		{
			

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
		}

		

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\2ABE7DD7AD111644CF213A58CDC32B2090C5\3\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              

		
	}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Home_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Home_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                  
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
	{
		if (role == "Admin")
		{
			

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
			

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

		}
		if (role == "Admin" || role == "SuperLinea")
		{
			

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
		}

		

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              

		
	}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Home_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Home_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                  
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
	{
		if (role == "Admin")
		{
			

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
			

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

		}
		if (role == "Admin" || role == "SuperLinea")
		{
			

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  

			

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
		}

		

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              

		
	}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                  
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        if (role == "Admin")
        {
            

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 24 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                       
        }
        else if (role == "SuperCalidad")
        {
            

#line default
#line hidden

#line 25 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 26 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
        }
        else if (role == "SuperLinea")
        {
        

#line default
#line hidden

#line 27 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 28 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 29 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 30 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 31 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 32 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 33 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 34 "C:\Users\user\AppData\Local\Temp\318FFC68ABFF20CD581E07E8FF0578B3B1EA\2\ControlDeCalzado.git.augusto.cesar.paz\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
     }
   }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Inicio";
    var role = string.Empty;
    if (Request.IsAuthenticated)
    {
        role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;
    }


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = Common.CurrentUser.Get.Name;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                  
        

#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            __o = role;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                           
    }
    else
    {
        

#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                              
        

#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                                        
        

#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                __o = Url.Action("Login", "Account");


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
    if (Request.IsAuthenticated)
    {
        if (role == "Admin")
        {
            

#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Color");


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Modelo");


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
            

#line default
#line hidden

#line 24 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                       
        }
        else if (role == "SuperCalidad")
        {
            

#line default
#line hidden

#line 25 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                                   __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 26 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                  
        }
        else if (role == "SuperLinea")
        {
        

#line default
#line hidden

#line 27 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "LineaDeProduccion");


#line default
#line hidden

#line 28 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 29 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "Defecto");


#line default
#line hidden

#line 30 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 31 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "OrdenDeProduccion");


#line default
#line hidden

#line 32 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 33 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
                               __o = Url.Action("Index", "Turno");


#line default
#line hidden

#line 34 "C:\Users\user\AppData\Local\Temp\4E41871F206EC196E1D0BB11BA318030115B\3\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\Home\Index.cshtml"
              
     }
   }

#line default
#line hidden
}
}
}
