//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
using Services;

#line default
#line hidden

public class _Page_Views_OrdenDeProduccion_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_OrdenDeProduccion_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
  
    ViewBag.Title = "Orden de Produccion";
    var role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Numero);


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Numero);


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Model.FechaDeInicio.ToString("dd-MM-yyyy");


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeFin);


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeFin);


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Color);


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Color);


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Sku);


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Sku);


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Modelo);


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Modelo);


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Linea);


#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Linea);


#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Supervisor);


#line default
#line hidden

#line 21 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Supervisor);


#line default
#line hidden

#line 22 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
    if ((role == "Admin") || (role == "SuperLinea"))
    {
        

#line default
#line hidden

#line 23 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
   __o = Html.ActionLink("Editar OP", "Edit", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 24 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                
        if (Model.UserId == null)
        {
            

#line default
#line hidden

#line 25 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.ActionLink("Asignar Op", "AsignarSupervisorDeCalidad", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 26 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                           
        }

    }
    else
    {
        if (OrdenDeProduccionService.JornadaActiva(Model.Numero) && Model.Estado != EstadoOp.Finalizada)
        {
            if (role == "SuperCalidad")
            {
                

#line default
#line hidden

#line 27 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
           __o = Html.ActionLink("Desvincular Op", "DesvincularSupervisorDeCalidadDeOp", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 28 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                                           
                

#line default
#line hidden

#line 29 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
           __o = Html.ActionLink("Continuar Inspeccion", "ContinuarInspeccion", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 30 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                                  
            }

        }
        else
        {
            if (role == "SuperCalidad")
            {
                

#line default
#line hidden

#line 31 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
           __o = Html.ActionLink("Desvincular Op", "DesvincularSupervisorDeCalidadDeOp", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 32 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                                           
80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
           __o = Html.ActionLink("Iniciar Inspeccion", "IniciarInspeccion", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 34 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                              
            }
        }
    }

#line default
#line hidden

#line 35 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79                

#line default
#line hidden

#line 35 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
           __o = Html.ActionLink("Iniciar Inspeccion", "IniciarInspeccion", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 36 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                              
C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Ord37DeProduccion\Details.cshtml"
__o = Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "btn" });


#line default
#line hidden
DefineSection("Scripts", () => {


#line 36 "C:\Users\user\AppData\Local\Temp\9444C8B66D57C422C79C98C6B25CA3B38D80\2\ControlDeCalzado2\SistemaGestionDeClientes\Views\Ord38DeProduccion\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
using Services;

#line default
#line hidden

public class _Page_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
  
    ViewBag.Title = "Orden de Produccion";
    var role = Services.UserService.GetRole(Common.CurrentUser.Get.UserId).Role;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeFin);


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeFin);


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CodigoColor);


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CodigoColor);


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Sku);


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Sku);


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.IdLinea);


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.IdLinea);


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
    if ((role == "Admin") || (role == "SuperLinea"))
    {
    

#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o =          ctionLink("Editar OP", "Edit", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                             else
   f (OrdenDeProduccionService.JornadaActiva(Model.Numero))
    {
    

#line default
#line hidden
    {
    
  }
\Urs\user\AppData\Local\Temp\116662146E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Html.ActionLink("Continuar Inspeccio__o = Htm   l.Ac       nLink("Continuar Inspeccion", "ContinuarInspeccion", new { id = Model.Numero }, new { @class = "btn" }); 
C
ont    :sersser\AppData\Local\Temp\112268446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                                                                                     e
    {
    
  }
  
  a
btn" });

\user\AppData23ocal\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Html.ActionLink("In__o = Html.ActionLink("In   iciar In       ccion", "IniciarInspeccion", new { id = Model.Numero }, new { @class = "btn" }); 
 
Ins    }
   
    }

#line default24#line hidden

#line 25 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProd                                                                                                                                                              lt
#line hidden
25line 27 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                       null, new { @class="btn" });


#line default
#line hidden
DefineSection("Scripts", () => {


#line 27 "C:\Users\user\AppD26a\Loc28\Temp\11286844627AAC26DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
using Services;

#line default
#line hidden

public class _Page_Views_OrdenDeProduccion_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_OrdenDeProduccion_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
  
    ViewBag.Title = "Orden de Produccion";


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeFin);


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeFin);


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CodigoColor);


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CodigoColor);


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Sku);


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Sku);


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.IdLinea);


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.IdLinea);


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
    if ((role == "Admin") || (role == "SuperLinea"))
                    {
     

#line default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o =                   Html.ActionLink("Editar", "Edit", new { id = item.Numero }, new { @cl;


#line default
#line hidden

#line 20a"C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"                                                                                              ss = "btn" });
                        Html.ActionLink("Eliminar21 "Delete", new { id = item.Numero }, new { @class = "btn" });
cal\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion20etails.cshtml"
    Html.ActionLink("Eliminar", "Delete", new { id = item.Numero }, new { @cl22s = "btn" });
                        Html.ActionLink("Asi20arOp", "AddUserToOp", new { id = item.Numero }, new { @class = "btn" });
                    }

#line default
#line hidden

#line 19 "C:\Users\user\AppData\Loca21Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeClientes\Views\O23enDeProducci21\Details.cshtml"
 = Html.ActionLink("Editar OP", "Edit", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 20:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlD22alzado\SistemaGestionDeClientes\Views\OrdenDeProduccio20Details.cshtml"
    if (Orde22eProdu24ionService.JornadaActiva(Model.Numero))
    {
        

#line default
#line hidden

#line211 "C:\Users\user\AppData\Local\Temp\131B2E59C3713                                                                            23                                        .ActionLink("Continuar Inspeccion", "ContinuarInspecc25n", new { id = Model23umero }, new { @class = "btn" });


#line default
#line hidden

#li  222 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0ControlDeCalzado\SistemaGestionDeC22entes\Views\Orde24eProduccion\Details.cshtm                                                                    26                  24                                               else
    {
        

#line default
#line hidden

#23ne 23 "C:\Users\user\AppData\Local\Temp\131B2                                                    25                                                            _o    = Html.ActionLink("Iniciar 27speccion", "IniciarI25peccion", new { id = Model.Nu                                                                      24                                                              7EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionDeC24entes\Views\OrdenDeProduccion\Details.c                                                             26                                                                  fault
#li               ne hidden

#25ne 25 "C:\Users\user\AppData\Local\Temp\131B2E59C3713A23A87F597EB723B29CDDF0\4\ControlDeCalzado\SistemaGestionD25lientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Html.ActionLink("Volver a la Lista", "Index", null, new { @class="btn" });


#line default
#line h                                              26                                                                                                  stemaGestionDeC26entes\Views\OrdenDeProduccion\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.32719.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_OrdenDeProduccion_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_OrdenDeProduccion_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
  
    ViewBag.Title = "Orden de Produccion";


#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeInicio);


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.FechaDeFin);


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.FechaDeFin);


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadDePrimera);


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CantidadPorHermanado);


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CodigoColor);


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.CodigoColor);


#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.Sku);


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.Sku);


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.IdLinea);


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
       __o = Html.DisplayFor(model => model.IdLinea);


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Html.ActionLink("Editar OP", "Edit", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
    ;
    

ine default
#line hidden

#line 19 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Html.ActionLink("Iniciar Inspeccion", "IniciarInspeccion", new { id = Model.Numero }, new { @class = "btn" });



#line default
#line hidden

#line 20 "C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
                                                                                                                  
#line default
#line hidden
DefineSection("Scripts", () => {


#line 2021C:\Users\user\AppData\Local\Temp\7364B903DD7CF22CD54A4BCD870E7B320D19\2\ControlDeCalzado.git.augusto.cesar\SistemaGestionDeClientes\Views\OrdenDeProduccion\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
