//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
using Common;

#line default
#line hidden

#line 3 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
using System.Text.RegularExpressions;

#line default
#line hidden

public class _Page_Inspeccionar_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Inspeccionar_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
__o = model;


#line default
#line hidden

#line 4 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
  
    ViewBag.Title = "Inspeccionar";


#line default
#line hidden

#line 5 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                         __o = Model.FechaDeInicio.ToString(<;<;


#line default
#line hidden

#line 6 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                               __o = el.IdLinea<;<;


#line default
#line hidden

#line 7 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                             __o = el.Sku<;<;


#line default
#line hidden

#line 8 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                __o = wBag.Modelo.Denominacion<;<;


#line default
#line hidden

#line 9 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                      __o = el.CodigoColor<;<;


#line default
#line hidden

#line 10 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                               __o = wBag.Color.DescripcionColor<;<;


#line default
#line hidden

#line 11 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                          __o = Model.CantidadDePrimera;


#line default
#line hidden

#line 12 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
            foreach (var item in ViewBag.DefectosO)
            {
                

#line default
#line hidden

#line 13 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                                                           item.IdDefecto;


#line default
#line hidden

#line 14 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                                                                             item.IdDefecto;


#line default
#line hidden

#line 15 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                                                                                                          (int)Pie.Izquierdo;


#line default
#line hidden

#line 16 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                                                                                                                                (int)TipoDefecto.Observado;


#line default
#line hidden

#line 17 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                    item.IdDefecto;


#line default
#line hidden

#line 18 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                                                                   __o = item.IdDefecto;


#line default
#line hidden

#l19e 20 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                               __o = item.IdDefecto;


#line default
#line hidden

#l20e 21 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                            __o = (int)Pie.Izquierdo;


#line default
#line hidden

#l21e 22 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                                                  __o = (int)TipoDefecto.Observado;


#line default
#line hidden

#l22e 23 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                       __o = Html.Raw(item.DescripcionDefecto);


#line default
#line hidden

#l23e 24 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                             __o = item.IdDefecto;


#line default
#line hidden

#l24e 25 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                               __o = item.IdDefecto;


#line default
#line hidden

#l25e 26 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                          __o = (int)Pie.Derecho;


#line default
#line hidden

#l26e 27 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                                              __o = (int)TipoDefecto.Observado;


#line default
#line hidden

#l27e 28 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                      __o = item.IdDefecto;


#line default
#line hidden

#l28e 29 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                             __o = item.IdDefecto;


#line default
#line hidden

#l29e 30 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                               __o = item.IdDefecto;


#line default
#line hidden

#l30e 31 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                          __o = (int)Pie.Derecho;


#line default
#line hidden

#l31e 32 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                                                                                                                                                              __o = (int)TipoDefecto.Observado;


#line default
#line hidden

#l32e 33 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.c                         
            }

#line default
#line hidden

#l33e 34 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
            foreach (var item in ViewBag.DefectosR)
            {
                

#line default
#line hidden

#l34e 35 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                                                                                 __o = item.IdDefecto;


#line default
#line hidden

#l35e 36 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                                                                                                   __o = item.IdDefecto;


#line default
#line hidden

#l36e 37 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                                                                                                                                __o = (int)Pie.Izquierdo;


#line default
#line hidden

#l37e 38 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                                                                                                                                                      __o = (int)TipoDefecto.Reproceso;


#line default
#line hidden

#l38e 39 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                          __o = item.IdDefecto;


#line default
#line hidden

#l39e 40 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccion                                                                                                 __item.IdDefectoo = item.IdDefecto;


#line default
#line hidden

#l40e 41 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                 __o = item.IdDefecto;


#line default
#line hidden

#l41e 42 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                                  (int)Pie Izquierdoo = item.IdDefecto;


#line default
#line hidden

#l42e 43 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                                                             TipoDefecto Reproceso(int)Pie.Izquierdo;


#line default
#line hidden

#l43e 44 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                             Html.Raw item.DescripcionDefecto oDefecto.Reproceso;


#line default
#line hidden

#l44e 45 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                      __IdDefectoescripcionDefecto);


#line default
#line hidden

#l45e 46 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                 __o = item.IdDefecto;


#line default
#line hidden

#l46e 47 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                                (int)Pie Derechoo = item.IdDefecto;


#line default
#line hidden

#l47e 48 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                                                                         TipoDefecto Reproceso= (int)Pie.Derecho;


#line default
#line hidden

#l48e 49 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                            item=IdDefectooDefecto.Reproceso;


#line default
#line hidden

#l49e 50 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProducc                                                                                                                             __o = item.IdDefecto;


#line50efault
#line hidden

#l51e 52 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\                                                                                                                                               __o = item.IdDefecto;


#line51efault
#line hidden

#l52e 53 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\                                                                                                                                                              (int)Pie Derechoo = item.IdDefecto;


#line52efault
#line hidden

#l53e 54 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\                                                                                                                                                                                       TipoDefecto Reproceso= (int)Pie.Derecho;


#line53efault
#line hidden

#l54e 55 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\                 peccionar.cshtml"
                     
            }

#line54efault
#lin55hidden

#l56e 57 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\   Local6Ca DetallesFC5759PausarSistemaPausarOplientes\Views\OrdenDeP__o = Html.ActionLink("Pausar OP", "Details", "stemaGestionDeClientes\Views\OrdenDeProdu
#line 55 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
   __o = Html.ActionLink("Terminar OP", "TerminarOp", "OrdenDeProduccion", new { id = Model.Numero }, new { @class = "btn" });


#line default
#line hidden
cci55\Inspeccionar.cshtml"
FC5759EA5DDFDD3\56ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
roduccion\Inspeccionar.cshtml"
__o = Html.ActionLink("Terminar OP", "Details", "OrdenDeProdu57ion", new { id = Model.Nu56ro }, new { @class = "btn" });


#li57 default
#line hidden
DefineSectio57"Scripts", (57=> {


#l58e 59 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClie58es\Views\OrdenDeProduccion\I57peccionar.cshtml"
__o = Scripts.Render58~/bundles/jqueryval");


#line58efault
#lin58hidden

#l59e 60 "C:\Users\user\AppData\Loca                            __o = Model.Numero;


#line default
#line hidden

#line 59 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC58FC5759EA5DDFDD3\3\ControlDeCalzado\Sist59aGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
l\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Insp59ci60ar.cshtml"
                 __o = eProduccion\Inspecc59nar.cshtml"
__o = Scripts.Re;;;;


60ine59efault
#lin59hidden

#l60e 61 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Insp60ci61ar.cshtml"
                                        60  __o = .Action("ActualizarCant;;;;

61#line60efault
#lin60hidden

#l61e 62 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\In61ec62onar.cshtml"
                 __o = 
                                            __o;;;;


#line61efault
#lin61hidden

#l62e 63 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                __o = ction("RegistrarDefecto;;;;


#line default
#line hidden
});

}
}
}
en

#line 61 "C:\Users\user\AppData\Local\Temp\116668446E4AAC94DEC00FC5759EA5DDFDD3\3\ControlDeCalzado\SistemaGestionDeClientes\Views\OrdenDeProduccion\Inspeccionar.cshtml"
                                                __o = ViewBag.IdHorarioDeControl;


#line default
#line hidden
});

}
}
}
